### ISSUE TITLE
Will changing something from Int64 to String break PostgreSQL logs?

### ISSUE THREAD

**Issue by jonathanjouty** [scrive/log-utils#2]
This is essentially a question for @arybczak.

Today we have some `newtype` wrapped `Int64` that we use as `Identifier` (from `log` package).
For example:

```
instance Identifier FooID Int64 where
...
```

The problem is that with `stdout` logs the `Int64` ends up something like `1.12345678e8`, which is ugly and makes searching between different logs annoying.

The question is whether changing the above to:

```
instance Identifier FooID String where
...
```

is likely to break anything?

**Comment by arybczak** [comment]
The serialization seems to depend on aeson version, this is with aeson-1.0.1.0:

```
λ> encode $ object ["asd" .= (123456789::Int64) ]
"{\"asd\":123456789}"
```

**Comment by 23Skidoo** [comment]
> The serialization seems to depend on aeson version, this is with aeson-1.0.1.0:

This is with 0.11.2.0:

```
> encode $ object ["asd" .= (123456789::Int64) ]
"{\"asd\":123456789}"
```

So the problem seems to lie elsewhere.

**Comment by arybczak** [comment]
It also probably depends on version of scientific, as Number in aeson is represented as Scientific.

It's probably best to inspect how encode function prints numbers in the aeson version you use.

**Comment by 23Skidoo** [comment]
Turns out it was an issue with the `aeson-pretty` package: https://github.com/informatikr/aeson-pretty/commit/d7a6c6e49d8c9e7a0de6a73f5fe2135d87568e8a.

**Comment by jonathanjouty** [comment]
Great! Should we close this issue in that case?

**Comment by 23Skidoo** [comment]
I guess so.
